- name: installing the catalogue component
  hosts: localhost
  become: yes
  tasks:
  - name: steup the npm source
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: install the nodejs
    ansible.builtin.yum: 
      name: nodejs
      state: installed