- name: installing the catalogue component
  hosts: localhost
  become: yes
  tasks:
  - name: steup the npm source
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: install the nodejs
    ansible.builtin.yum: 
      name: nodejs
      state: installed
  - name: checking the roboshp user exit or not 
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  
  - when: out.rc !=0 
    name: create the user
    become: yes
    ansible.builtin.user:
      name: roboshop
  - name: checking the directory is exist or not if not exist creaitng directoor
    ansible.builtin.stat:
      path: /app
    register: directoor

  - name: print the directory status
    ansible.builtin.debug:
      msg: "the status is {{directoor}}"
  
  - when: directoor.stat.exists == "false"
    name: create/app directory
    ansible.builtin.file:
      path: /app
      state: directory




    