- name: Checking the directory or not
  hosts: localhost
  become: yes
  tasks:
    - name: Checking if the user 'roboshop' exists
      ansible.builtin.command: id roboshop
      register: mohan

    - name: Printing the variable
      ansible.builtin.debug:
        msg: "The output of the variable is {{ mohan.stdout }}"
    
    - name: Check if the user exists
      ansible.builtin.debug:
        msg: "The user exists."
      when: mohan.rc == 0

    - name: Check if the user does not exist
      ansible.builtin.debug:
        msg: "The user does not exist."
      when: mohan.rc != 0
