- name: for loops
  hosts: localhost
  vars_prompt:
  - name: chiru
    prompt: mohan
    private: false

  tasks:
  - name: validating the variable
    ansible.builtin.debug:
      msg: "{{chiru[10:20]}}"