- name: for loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing the spackages
    ansible.builtin.yum:
      name:  "{{item.name}}"
      state: "{{item.state}}"
    loop:
      - {name: 'nginx', state: 'installed'}
      - {name: 'postfix' ,state: 'installed'}

  
