- name: for loops
  hosts: localhost
  vars_prompt:
  - name: this is from input
    prompt: mohan
    private: true

  tasks:
  - name: validating the variable
    ansible.builtin.debug:
      msg: "{{mohan}}"
