- name: for loops
  hosts: localhost
  vars_prompt:
  - name: chiru
    prompt: mohan
    private: false
  vars: 
  - mydetails:
    name: mohan
    age: 25
    weight: 80
      

  tasks:
  - name: validating the variable
    ansible.builtin.debug:
      msg: "{{mydetails}}"